version: '3'
networks:
  network-dashboard:
    driver: bridge

services:
  influxdb:
    container_name: influxdb
    image: influxdb:2.1-alpine
    networks:
      - network-dashboard
    ports:
      - '8086:8086'
    volumes:
      - influxdb-data:/var/lib/influxdb2
      - /etc/influxdb2:/etc/influxdb2

  grafana:
    container_name: grafana
    image: grafana/grafana
    networks:
      - network-dashboard
    user: "472:472"
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=password
      - GF_USERS_ALLOW_SIGN_UP=false  
    restart: always      

volumes:
  influxdb-data:
  grafana-data: